export const FETCH_TIME_ENTRIES_REQUEST = 'FETCH_TIME_ENTRIES_REQUEST';
export const FETCH_TIME_ENTRIES_SUCCESS = 'FETCH_TIME_ENTRIES_SUCCESS';
export const FETCH_TIME_ENTRIES_FAILURE = 'FETCH_TIME_ENTRIES_FAILURE';

export const DELETE_TIME_ENTRY_REQUEST = 'DELETE_TIME_ENTRY_REQUEST';
export const DELETE_TIME_ENTRY_SUCCESS = 'DELETE_TIME_ENTRY_SUCCESS';
export const DELETE_TIME_ENTRY_FAILURE = 'DELETE_TIME_ENTRY_FAILURE';

export const CREATE_TIME_ENTRY_REQUEST = 'CREATE_TIME_ENTRY_REQUEST';
export const CREATE_TIME_ENTRY_SUCCESS = 'CREATE_TIME_ENTRY_SUCCESS';
export const CREATE_TIME_ENTRY_FAILURE = 'CREATE_TIME_ENTRY_FAILURE';
