export const CREATE_TEAM_MEMBER_FAILURE = 'CREATE_TEAM_MEMBER_FAILURE';
export const CREATE_TEAM_MEMBER_REQUEST = 'CREATE_TEAM_MEMBER_REQUEST';
export const CREATE_TEAM_MEMBER_SUCCESS = 'CREATE_TEAM_MEMBER_SUCCESS';
export const FETCH_TEAM_MEMBERS_FAILURE = 'FETCH_TEAM_MEMBERS_FAILURE';
export const FETCH_TEAM_MEMBERS_REQUEST = 'FETCH_TEAM_MEMBERS_REQUEST';
export const FETCH_TEAM_MEMBERS_SUCCESS = 'FETCH_TEAM_MEMBERS_SUCCESS';
export const SORT_TEAM_MEMBERS_BY_FIELD = 'SORT_TEAM_MEMBERS_BY_FIELD';
